### ISSUE TITLE
Plugin crashes Sketch 3.3

### ISSUE THREAD

**Issue by pkvdesigns** [vrjbndr/select-next-artboard#2]
Hi, since updating to Sketch 3.3 the app crashes when using your plugin.
Is this a known issue? 

Thanks in advance for a response.

**Comment by vrjbndr** [comment]
I apologize for the late follow-up here, I'll look into this asap.

**Comment by machinic** [comment]
I came by to check in about the same thing. Love the plugin, btw, it has become essential to my workflow. I've been missing its use since the Sketch upgrade.

**Comment by vrjbndr** [comment]
This should be fixed! My apologies for taking so long to get around to this. Let me know if anyone's still running into issues!
